# Generated by Django 5.2.12 on 2026-07-17 11:01

# Django
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("eve_sde", "0021_archetype_freelancejobschema_and_more"),
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSovereignty",
            fields=[
                (
                    "solar_system_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "alliance_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "faction_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("shared", "Shared")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wh_maps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": (
                    ("basic_access", "Can access this app and create maps"),
                    ("admin_access", "Can manage and delete any map"),
                ),
            },
        ),
        migrations.CreateModel(
            name="MapSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("pinned", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="wh_mapper.map",
                    ),
                ),
                (
                    "solar_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("map", "solar_system")},
            },
        ),
        migrations.CreateModel(
            name="WormholeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                (
                    "leads_to_class",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("max_mass", models.FloatField(blank=True, default=None, null=True)),
                (
                    "max_jump_mass",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "max_stable_time",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "item_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wh_mapper_wormhole_type",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature_id", models.CharField(max_length=10)),
                (
                    "sig_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("wormhole", "Wormhole"),
                            ("combat", "Combat Site"),
                            ("data", "Data Site"),
                            ("relic", "Relic Site"),
                            ("gas", "Gas Site"),
                            ("ore", "Ore Site"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "life_status",
                    models.CharField(
                        choices=[
                            ("stable", "Stable"),
                            ("lt_48h", "< 48 hours"),
                            ("lt_24h", "< 24 hours"),
                            ("lt_12h", "< 12 hours"),
                            ("lt_4h", "< 4 hours"),
                            ("lt_1h", "< 1 hour"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                (
                    "life_status_marked_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "map_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="wh_mapper.mapsystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wormhole_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wh_mapper.wormholetype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("map_system", "signature_id")},
            },
        ),
        migrations.CreateModel(
            name="MapPresence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=255)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence",
                        to="wh_mapper.map",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("map", "channel_name")},
            },
        ),
        migrations.CreateModel(
            name="MapShare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("character", "Character"),
                            ("corporation", "Corporation"),
                            ("alliance", "Alliance"),
                        ],
                        max_length=11,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="wh_mapper.map",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "target_id"],
                "default_permissions": (),
                "unique_together": {("map", "scope", "target_id")},
            },
        ),
        migrations.CreateModel(
            name="MapShareGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_shares",
                        to="wh_mapper.map",
                    ),
                ),
            ],
            options={
                "ordering": ["group_id"],
                "default_permissions": (),
                "unique_together": {("map", "group")},
            },
        ),
        migrations.CreateModel(
            name="TrackedCharacter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "last_solar_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("added_by", "character")},
            },
        ),
        migrations.CreateModel(
            name="WormholeConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("wormhole", "Wormhole"),
                            ("stargate", "Stargate"),
                            ("ansiblex", "Ansiblex Jump Gate"),
                        ],
                        default="wormhole",
                        max_length=10,
                    ),
                ),
                (
                    "life_status",
                    models.CharField(
                        choices=[
                            ("stable", "Stable"),
                            ("lt_48h", "< 48 hours"),
                            ("lt_24h", "< 24 hours"),
                            ("lt_12h", "< 12 hours"),
                            ("lt_4h", "< 4 hours"),
                            ("lt_1h", "< 1 hour"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                (
                    "life_status_marked_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "mass_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("fresh", "Fresh"),
                            ("reduced", "Reduced"),
                            ("critical", "Critical"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "ship_size_limit",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("capital", "Capital"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bottom_signature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connection_as_bottom",
                        to="wh_mapper.signature",
                    ),
                ),
                (
                    "bottom_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_as_bottom",
                        to="wh_mapper.mapsystem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="wh_mapper.map",
                    ),
                ),
                (
                    "top_signature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connection_as_top",
                        to="wh_mapper.signature",
                    ),
                ),
                (
                    "top_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_as_top",
                        to="wh_mapper.mapsystem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("map", "top_system", "bottom_system")},
            },
        ),
    ]
