# Generated by Django 5.2.12 on 2026-07-17 12:52

# Django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wh_mapper", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wormholeconnection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="signature",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="wormholeconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("connection_type", "stargate")),
                fields=("map", "top_system", "bottom_system"),
                name="unique_stargate_connection_per_pair",
            ),
        ),
    ]
