# Generated by Django 5.2.12 on 2026-07-24 10:57

# Django
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0021_archetype_freelancejobschema_and_more"),
        ("wh_mapper", "0002_alter_wormholeconnection_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("shared", "Shared")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("found", models.BooleanField(default=False)),
                ("systems", models.JSONField(blank=True, default=list)),
                ("legs", models.JSONField(blank=True, default=list)),
                (
                    "last_computed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "end_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wh_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "start_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ConnectionFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_life_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stable", "Stable"),
                            ("lt_48h", "< 48 hours"),
                            ("lt_24h", "< 24 hours"),
                            ("lt_12h", "< 12 hours"),
                            ("lt_4h", "< 4 hours"),
                            ("lt_1h", "< 1 hour"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "suggested_mass_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unknown", "Unknown"),
                            ("fresh", "Fresh"),
                            ("reduced", "Reduced"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("suggests_collapsed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="wh_mapper.wormholeconnection",
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "default_permissions": (),
                "unique_together": {("connection", "flagged_by")},
            },
        ),
    ]
