# Generated by Django 5.2.12 on 2026-07-25 02:06

# Django
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wh_mapper", "0003_route_connectionflag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="legs",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="systems",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
