# Generated by Django 5.2.12 on 2026-07-25 07:31

# Django
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wh_mapper", "0004_alter_route_legs_alter_route_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="alternate",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
