# Generated by Django 5.2.12 on 2026-08-01 05:54

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0022_sovereigntyupgrade"),
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("wh_mapper", "0006_mapcontribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="map",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("basic_access", "Can access this app and create maps"),
                    ("admin_access", "Can manage and delete any map"),
                    (
                        "backseat_fc",
                        "Can operate fleet tracking on behalf of another character",
                    ),
                ),
            },
        ),
        migrations.AddField(
            model_name="wormholeconnection",
            name="mass_crossed",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="FleetTrackingSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fleet_id", models.BigIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_polled_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                (
                    "fc_character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="FleetMemberState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.PositiveIntegerField()),
                (
                    "character_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("ship_type_id", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_solar_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.solarsystem",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="wh_mapper.fleettrackingsession",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("session", "character_id")},
            },
        ),
        migrations.CreateModel(
            name="FleetTrackingWatcher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attached_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="wh_mapper.fleettrackingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("session", "user")},
            },
        ),
    ]
