# Generated by Django 5.2.12 on 2026-08-08 06:41

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wh_mapper",
            "0007_alter_map_options_wormholeconnection_mass_crossed_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHeartbeat",
            fields=[
                (
                    "task_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("last_run_at", models.DateTimeField()),
                ("last_success", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
