# Generated by Django 5.2.12 on 2026-08-10 12:31

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wh_mapper", "0008_taskheartbeat"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStatic",
            fields=[
                (
                    "solar_system_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("codes", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
