# Generated by Django 5.2.12 on 2026-08-22 06:06

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wh_mapper", "0009_systemstatic"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="read_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="wormholeconnection",
            name="ship_size_limit",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("xlarge", "X-Large"),
                    ("capital", "Capital"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
    ]
